<?php

namespace app\models\forms;

use yii\base\Model;

class DishForm extends Model
{
    public ?int $id = null;
    public ?string $dish_name_en = null;
    public ?string $dish_name_ru = null;
    public ?string $dish_name_kk = null;
    public array $composition = [];
    public ?string $dish_price = null;
    public ?string $dish_photo = null;
    public ?string $type = null;

    public function rules(): array
    {
        return ([
            [['dish_name_en', 'dish_name_ru', 'dish_name_kk', 'composition',
                'dish_price', 'dish_photo', 'type'], 'required']
        ]);
    }

    public function attributeLabels(): array
    {
        return [
            'dish_name_en'=>'Name of dish en',
            'dish_name_ru'=>'Name of dish ru',
            'dish_name_kk'=>'Name of dish kz',
            'composition'=>'Composition',
            'dish_price'=>'Price',
            'dish_photo'=>'Photo',
            'type'=>'Type'
        ]; // TODO: Change the autogenerated stub
    }

}